-- Insertar 300 temas de investigación profunda en la categoría Personajes
DO $$
DECLARE
  personajes_category_id UUID;
BEGIN
  -- Obtener el ID de la categoría Personajes
  SELECT id INTO personajes_category_id FROM categories WHERE name = 'Personajes';
  
  IF personajes_category_id IS NULL THEN
    RAISE EXCEPTION 'La categoría Personajes no existe. Ejecuta primero create_categories_only.sql';
  END IF;
  
  -- Insertar los 300 temas de investigación profunda
  INSERT INTO topics (title, category_id, mode) 
  SELECT 
    unnest(ARRAY[
      'El efecto Mandela',
      'El efecto de desinformación',
      'El paradigma DRM y la creación de falsos recuerdos',
      'Los errores de atribución de la fuente de un recuerdo',
      'La criptomnesia',
      'El déjà vu',
      'El jamais vu',
      'El fenómeno de "tenerlo en la punta de la lengua"',
      'El efecto Zeigarnik',
      'El efecto Von Restorff',
      'El efecto de espaciamiento',
      'El efecto de prueba',
      'El efecto de generación',
      'El efecto de primacía',
      'El efecto de recencia',
      'El "reminiscence bump" o pico de reminiscencia',
      'La retrospección color de rosa',
      'La regla del pico y el final',
      'El abandono de la duración',
      'El sesgo retrospectivo',
      'El sesgo de confirmación',
      'La perseverancia de las creencias',
      'La polarización de creencias',
      'La disonancia cognitiva',
      'La teoría del proceso irónico',
      'El efecto rebote de la supresión de pensamientos',
      'La ilusión de profundidad explicativa',
      'La maldición del conocimiento',
      'La ilusión de transparencia',
      'El efecto foco o "spotlight effect"',
      'El efecto de falso consenso',
      'El efecto halo',
      'El efecto cuerno',
      'El error fundamental de atribución',
      'La asimetría actor-observador',
      'El sesgo de autoservicio',
      'La hipótesis del mundo justo',
      'El efecto Dunning-Kruger',
      'El fenómeno del impostor',
      'El efecto Barnum o Forer',
      'El efecto de mera exposición',
      'El efecto de verdad ilusoria',
      'El efecto durmiente',
      'La ilusión del enfoque',
      'El efecto de anclaje',
      'El efecto de encuadre',
      'La heurística de disponibilidad',
      'La heurística de representatividad',
      'La heurística afectiva',
      'La falacia de conjunción',
      'El abandono de la tasa base',
      'El sesgo de resultado',
      'El sesgo de omisión',
      'El sesgo de acción',
      'El sesgo del statu quo',
      'El efecto de opción predeterminada',
      'El efecto dotación',
      'La aversión a la pérdida',
      'La falacia del coste hundido',
      'La escalada del compromiso',
      'El principio de compromiso y consistencia',
      'El sesgo del presente',
      'El descuento hiperbólico',
      'La contabilidad mental',
      'El efecto "dinero de la casa"',
      'El efecto disposición en los inversores',
      'El efecto señuelo',
      'El efecto compromiso o alternativa intermedia',
      'El efecto precio cero',
      'El efecto de escasez',
      'La sobrecarga de elección',
      'La paradoja de la elección',
      'El efecto IKEA',
      'La justificación del esfuerzo',
      'El efecto gradiente de meta',
      'La falacia de planificación',
      'El sesgo de optimismo',
      'El sesgo de normalidad',
      'El sesgo de negatividad',
      'El sesgo del superviviente',
      'El sesgo de publicación',
      'El efecto farola',
      'La falacia del francotirador de Texas',
      'La falacia del jugador',
      'La falacia o efecto de la mano caliente',
      'La ilusión de agrupamiento',
      'La ley de los pequeños números',
      'La regresión a la media',
      'La ilusión de control',
      'El sesgo de exceso de confianza',
      'El efecto difícil-fácil',
      'El efecto "mejor que la media"',
      'El sesgo de información',
      'La aversión a la ambigüedad',
      'El efecto certeza',
      'El efecto pseudocerteza',
      'El abandono de la probabilidad',
      'El sesgo de riesgo cero',
      'El efecto de la víctima identificable',
      'El abandono del alcance',
      'El abandono del denominador',
      'El sesgo de proporción',
      'El efecto espectador',
      'La difusión de responsabilidad',
      'La ignorancia pluralista',
      'El pensamiento grupal',
      'La polarización grupal',
      'La holgazanería social',
      'La facilitación social',
      'La desindividualización',
      'Los experimentos de conformidad de Asch',
      'El experimento de obediencia de Milgram',
      'El experimento de la prisión de Stanford y las críticas posteriores',
      'El experimento de la Cueva de los Ladrones',
      'El paradigma del grupo mínimo',
      'La amenaza del estereotipo',
      'El efecto Pigmalión',
      'El efecto Golem',
      'La profecía autocumplida',
      'La prueba social',
      'La norma de reciprocidad',
      'La técnica del pie en la puerta',
      'La técnica de la puerta en la cara',
      'La técnica de la bola baja',
      'La reactancia psicológica',
      'El efecto boomerang',
      'La teoría de la comparación social',
      'La privación relativa',
      'El efecto de homogeneidad del exogrupo',
      'El favoritismo del endogrupo',
      'El error último de atribución',
      'La hipótesis del contacto',
      'Las relaciones parasociales',
      'El número de Dunbar',
      'El contagio emocional',
      'El contagio social',
      'La teoría de las ventanas rotas y la controversia sobre su evidencia',
      'La espiral del silencio',
      'El efecto de tercera persona',
      'El efecto de medios hostiles',
      'El efecto de falsa singularidad',
      'La inhibición social',
      'El efecto Ringelmann',
      'La tragedia de los comunes',
      'El problema del polizón o "free rider"',
      'El dilema del voluntario',
      'El dilema del prisionero',
      'La caza del ciervo o "Stag Hunt"',
      'El juego del gallina o Hawk-Dove',
      'El juego del ciempiés',
      'El juego del ultimátum',
      'El juego del dictador',
      'El juego de la confianza',
      'El juego de bienes públicos',
      'La guerra de desgaste',
      'La batalla de los sexos',
      'El juego de las monedas coincidentes',
      'El juego de la minoría',
      'El concurso de belleza de Keynes',
      'Los puntos focales de Schelling',
      'El equilibrio de Nash',
      'La paradoja de la inducción hacia atrás',
      'La paradoja de la cadena de tiendas',
      'El dilema del viajero',
      'La paradoja de Braess',
      'La paradoja de Parrondo',
      'El problema de Newcomb',
      'La paradoja de Ellsberg',
      'La paradoja de Allais',
      'La paradoja de San Petersburgo',
      'El problema de la secretaria',
      'El problema de Monty Hall',
      'La paradoja de la Bella Durmiente',
      'La paradoja de los dos sobres',
      'La paradoja del cumpleaños',
      'La paradoja del niño o la niña',
      'La paradoja de las cajas de Bertrand',
      'La paradoja de Bertrand sobre las cuerdas de un círculo',
      'La paradoja de Simpson',
      'La paradoja de Berkson',
      'La falacia del fiscal',
      'La paradoja del falso positivo',
      'La paradoja de la amistad',
      'La paradoja de inspección',
      'La paradoja de Condorcet',
      'El teorema de imposibilidad de Arrow',
      'El teorema de Gibbard-Satterthwaite',
      'La paradoja del voto',
      'La paradoja de Jevons',
      'La tragedia de los anticomunes',
      'La maldición del ganador',
      'El riesgo moral',
      'El problema principal-agente',
      'La maldición de los recursos naturales',
      'La enfermedad holandesa',
      'La paradoja de Easterlin',
      'La paradoja del ahorro',
      'La ley de Goodhart',
      'El efecto cobra',
      'El efecto Streisand',
      'La habitación de Mary',
      'La habitación china de Searle',
      'Los zombis filosóficos',
      'El cerebro en una cubeta',
      'El genio maligno de Descartes',
      'La máquina de experiencias de Nozick',
      'El barco de Teseo',
      'La paradoja de la teletransportación',
      'El experimento mental del Hombre del Pantano',
      'El experimento de la Tierra Gemela',
      'El espectro invertido',
      'El molino de Leibniz',
      'Los experimentos de cerebro dividido y la identidad personal',
      'La fisión personal de Derek Parfit',
      'El dilema del tranvía',
      'La variante del hombre gordo del dilema del tranvía',
      'El dilema del cirujano de trasplantes',
      'El violinista de Judith Jarvis Thomson',
      'El niño que se ahoga de Peter Singer',
      'El velo de la ignorancia de John Rawls',
      'El monstruo de utilidad',
      'La conclusión repugnante de Derek Parfit',
      'El problema de la no identidad',
      'La paradoja de la mera adición',
      'La objeción de la exigencia extrema al utilitarismo',
      'La ética del bote salvavidas',
      'El dilema de Heinz',
      'El dilema de Eutifrón',
      'La paradoja de la omnipotencia',
      'El problema del mal',
      'El conflicto entre presciencia y libre albedrío',
      'La apuesta de Pascal',
      'El atraco de Pascal o "Pascal''s Mugging"',
      'El asno de Buridán',
      'El problema de Molyneux',
      'El problema de Gettier',
      'El caso del granero falso',
      'La paradoja de la lotería',
      'La paradoja del prefacio',
      'La paradoja de Moore',
      'La paradoja del examen sorpresa',
      'La paradoja de Menón',
      'La paradoja de cognoscibilidad de Fitch',
      'La paradoja del mentiroso',
      'La paradoja de Curry',
      'La paradoja de Grelling-Nelson',
      'La paradoja de Berry',
      'La paradoja de Richard',
      'La paradoja de Yablo',
      'La paradoja Sorites o paradoja del montón',
      'La paradoja de Russell',
      'La paradoja del barbero',
      'La paradoja del cuervo',
      'La paradoja de "grue" de Goodman',
      'El nuevo enigma de la inducción',
      'El hotel infinito de Hilbert',
      'La paradoja de Banach-Tarski',
      'La paradoja de Aquiles y la tortuga',
      'La paradoja de la dicotomía de Zenón',
      'La lámpara de Thomson',
      'La paradoja de Ross-Littlewood',
      'La paradoja de Galileo sobre el infinito',
      'La paradoja de Skolem',
      'El cuerno de Gabriel',
      'La paradoja de la línea de costa',
      'La hormiga sobre una cuerda elástica',
      'El teorema del mono infinito',
      'El cerebro de Boltzmann',
      'El argumento del Juicio Final',
      'El argumento de la simulación de Nick Bostrom',
      'La paradoja de Fermi',
      'El Gran Filtro',
      'La ecuación de Drake',
      'El principio antrópico',
      'El problema del ajuste fino del universo',
      'La paradoja de Olbers',
      'La paradoja de los gemelos',
      'La paradoja del abuelo',
      'La paradoja bootstrap o bucle causal',
      'El demonio de Maxwell',
      'El gato de Schrödinger',
      'El amigo de Wigner',
      'El efecto Zenón cuántico',
      'La paradoja EPR de Einstein-Podolsky-Rosen',
      'El teorema de Bell y la no localidad cuántica',
      'La paradoja de la información de los agujeros negros',
      'La paradoja del firewall de los agujeros negros',
      'El problema de la medición cuántica',
      'El experimento de elección retardada de Wheeler',
      'El borrador cuántico de elección retardada',
      'El demonio de Laplace',
      'La flecha del tiempo y la paradoja de la entropía',
      'El efecto Mpemba',
      'La paradoja del Sol joven débil',
      'La hipótesis de la Reina Roja',
      'La paradoja de Peto',
      'La paradoja del enriquecimiento ecológico',
      'La hipótesis de la Tierra Rara',
      'La hipótesis del zoológico como solución a la paradoja de Fermi',
      'La hipótesis del Bosque Oscuro'
    ]),
    personajes_category_id,
    'profundo';
    
  RAISE NOTICE '300 temas de investigación profunda insertados correctamente';
END $$;

-- Verificar que se insertaron correctamente
SELECT 
  COUNT(*) as temas_profundo_totales
FROM topics
WHERE mode = 'profundo';
